import { Link } from "wouter";
import SEO from "@/components/site/SEO";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const HOMEPAGE_JSONLD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://precisehire.com/#org",
      name: "Precise Hire",
      url: "https://precisehire.com/",
      foundingDate: "2003-01-01",
      slogan: "Background checks employers actually trust.",
      sameAs: [],
    },
    {
      "@type": "WebSite",
      "@id": "https://precisehire.com/#site",
      url: "https://precisehire.com/",
      name: "Precise Hire",
      publisher: { "@id": "https://precisehire.com/#org" },
    },
    {
      "@type": "Service",
      name: "Employment Background Checks",
      provider: { "@id": "https://precisehire.com/#org" },
      areaServed: "United States",
      serviceType: "Background screening, drug testing, MVR, employment & education verification",
    },
  ],
};


const screeningServices=[
 {category:'CRIMINAL BACKGROUND CHECKS',title:'Look deeper.\nHire with context.',description:'Thorough criminal record research helps you understand the information behind a hiring decision, with potential records verified at the source.',benefits:['County, state, federal, and national searches','Source verification of potential records','Clear reporting for an informed review'],link:'criminal-background-checks',label:'Explore criminal checks',icon:'<path d="m24 5 15 6v12c0 8-10 15-15 19-5-4-15-11-15-19V11Z"/><path d="m17 23 5 5 10-12"/>'},
 {category:'EMPLOYMENT VERIFICATION',title:'Experience matters.\nMake sure it adds up.',description:'Confirm the work history behind the résumé. Our team contacts previous employers and manages the follow-ups, so your recruiters can focus on their next conversation.',benefits:['Dates of employment and positions held','Direct contact with prior employers','Follow-up handled by our research team'],link:'employment-verification',label:'Explore employment verification',icon:'<rect x="7" y="14" width="34" height="27" rx="3"/><path d="M17 14V7h14v7M7 25h34M20 24v5h8v-5"/>'},
 {category:'DRUG & ALCOHOL TESTING',title:'A safer workplace.\nA supported process.',description:'Coordinate drug and alcohol screening with collection, lab analysis, and Medical Review Officer review as applicable to the test ordered.',benefits:['Testing options for your workplace needs','Collection and lab coordination','Results available with your screening information'],link:'drug-testing',label:'Explore drug & alcohol testing',icon:'<path d="M17 6h14M19 6v13L8 36a4 4 0 0 0 3 6h26a4 4 0 0 0 3-6L29 19V6M14 30h20"/>'},
 {category:'DRIVING RECORD CHECKS',title:'For the people\nbehind the wheel.',description:'Review driving history and license information for roles where time on the road is part of the job. Build a screening package around your drivers and fleet.',benefits:['Motor vehicle records across all 50 states','License status, class, and restrictions','Driving history to support your review'],link:'driving-record-checks-mvr',label:'Explore driving records',icon:'<rect x="4" y="10" width="40" height="28" rx="4"/><circle cx="16" cy="21" r="4"/><path d="M9 32c0-7 14-7 14 0M30 19h7M30 25h7M30 31h5"/>'},
 {category:'EDUCATION VERIFICATION',title:'Their credentials.\nYour clarity.',description:'Confirm academic qualifications with schools and issuing institutions. Get a clearer understanding of the education behind your candidate’s application.',benefits:['Degrees, diplomas, and school attendance','Verification with issuing institutions','Support for role-specific credential checks'],link:'education-verification',label:'Explore education verification',icon:'<path d="m3 17 21-10 21 10-21 10ZM11 22v12c8 6 18 6 26 0V22M44 18v17"/>'},
 {category:'INTERNATIONAL BACKGROUND CHECKS',title:'Across borders.\nClose attention.',description:'Support international hiring with research partners who understand local records and verification processes. Our team helps coordinate the details across countries.',benefits:['Country-specific screening options','Employment and education verification','Guidance on required documentation'],link:'international-background-checks',label:'Explore international screening',icon:'<circle cx="24" cy="24" r="19"/><ellipse cx="24" cy="24" rx="9" ry="19"/><path d="M5 24h38M9 13h30M9 35h30"/>'}
];
const serviceTitles=["Criminal background checks","Employment verification","Drug & alcohol testing","Driving record checks","Education verification","International screening"];
const serviceSummaries=["Thorough research. A clearer picture.","Confidence in the experience behind the résumé.","Screening that supports a safer workplace.","Know more about who is behind the wheel.","Confirm the qualifications that matter.","Careful research, across borders."];
function ServiceIcon({icon}:{icon:string}) { return <svg viewBox="0 0 48 48" aria-hidden="true" dangerouslySetInnerHTML={{__html:icon}}/>; }
function ServiceExplorer(){
 return <nav className="service-tabs" aria-label="Screening services">{screeningServices.map((service,i)=><Link key={service.link} href={`/services/${service.link}`} className="service-tab service-card-link"><ServiceIcon icon={service.icon}/><span className="service-card-copy"><strong>{serviceTitles[i]}</strong><small>{serviceSummaries[i]}</small></span><span className="card-selected">View service</span></Link>)}</nav>;
}
function HomeQuestions(){return <Accordion type="single" collapsible className="faq-list"><AccordionItem value="question-0"><AccordionTrigger>Which background checks do we need?</AccordionTrigger><AccordionContent><p >Your package should reflect the role, responsibilities, industry, and applicable requirements. A screening specialist can walk through your hiring process and help you choose relevant checks.</p></AccordionContent></AccordionItem><AccordionItem value="question-1"><AccordionTrigger>How long does screening take?</AccordionTrigger><AccordionContent><p >Timing depends on the searches ordered, court access, and responses from employers or schools. The team can explain expected timelines for your specific screening package.</p></AccordionContent></AccordionItem><AccordionItem value="question-2"><AccordionTrigger>Can PreciseHire work with our hiring software?</AccordionTrigger><AccordionContent><p >PreciseHire offers integrations and API options. Share the platform you use so the team can confirm availability and setup requirements.</p><Link href="/integrations">Explore integration options</Link></AccordionContent></AccordionItem><AccordionItem value="question-3"><AccordionTrigger>What will our screening package cost?</AccordionTrigger><AccordionContent><p >Pricing depends on the checks you need and your screening volume. Request a quote to review your package and any applicable third-party fees before getting started.</p><Link href="/get-a-quote">Request your custom quote</Link></AccordionContent></AccordionItem></Accordion>}
function ExampleReport(){return <DialogContent className="ph-report-dialog"><p className="eyebrow">ILLUSTRATIVE REPORT · SAMPLE DATA</p><DialogTitle>A clearer view<br/>of <em>what comes next.</em></DialogTitle><DialogDescription className="dialog-intro">A sample layout showing how completed checks could be presented for your team’s review.</DialogDescription><div className="sample-person"><span className="avatar" aria-hidden="true">AJ</span><div><strong>Alex Johnson</strong><span>Example candidate · Employment package</span></div></div>{["Criminal background","Employment verification","Education verification"].map(label=><div className="sample-check" key={label}><div><strong>{label}</strong><p>Check completed. Review the returned information.</p></div><span className="sample-status">Complete</span></div>)}<p className="sample-disclaimer">“Complete” indicates a finished check, not a hiring recommendation. This concept contains no real candidate information.</p><Link className="ph-button ph-button-red" href="/talk-to-an-expert">Ask for a platform walkthrough</Link></DialogContent>}
export default function Home(){return <><SEO title="Precise Hire — Background Checks Employers Trust" description="FCRA-compliant employment background checks, drug testing, MVR, and verifications — most reports back in under 4 hours. Trusted by employers for 22+ years." canonical="https://precisehire.com/" image="https://precisehire.com/images/hero-support-team.webp" keywords={["employment background check","FCRA compliant background check","pre-employment screening","criminal background check for employers","drug testing for employers","PBSA accredited background check"]} jsonLd={HOMEPAGE_JSONLD}/><Dialog><div className="ph-home">
<section className="hero" aria-labelledby="hero-heading"><div className="container hero-grid">
<div className="hero-copy"><p className="eyebrow"><span ></span> PEOPLE. PRECISION. PEACE OF MIND.</p><h1 id="hero-heading">The confidence<br />behind every<br /><em >great hire.</em></h1><p className="hero-description">Employment background checks with the clarity you need and the personal support you deserve. Make your next hiring decision a confident one.</p><div className="hero-actions"><Link className="button button-red" href="/get-a-quote">Get a custom quote</Link><a className="quiet-link" href="#screening">Explore our services</a></div><div className="hero-trust"><span className="trust-seal" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m12 3 8 3v6c0 4-5 7-8 9-3-2-8-5-8-9V6Z"/><path d="m8 12 3 3 5-6"/></svg></span><p ><strong >Experienced people. Thoughtful screening.</strong><br />Supporting employers for more than 20 years.</p></div></div>
<div className="hero-art"><img className="hero-swoosh" src="/images/swoosh-red.svg" alt="" aria-hidden="true"/><div className="photo-backing" aria-hidden="true"></div><div className="hero-photo"><img src="/images/hero-support-team.webp" alt="Support specialists pictured on the PreciseHire website" width="1400" height="1046" fetchPriority="high"/><div className="photo-bottom"><span className="small-rule"></span><p >Personal service.<br /><strong >At every step.</strong></p></div></div><div className="experience-seal"><strong >20<span >+</span></strong><span >YEARS OF<br />EXPERIENCE</span></div>
<DialogTrigger asChild><button className="report-card"><span className="report-top"><span className="report-badge" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 3h9l4 4v14H6Z M14 3v5h5 M9 13h7 M9 17h5"/></svg></span><span ><strong >Clarity, at a glance.</strong><small >ILLUSTRATIVE REPORT</small></span></span><span className="report-row"><span >Criminal background</span><span className="complete">✓ Complete</span></span><span className="report-row"><span >Employment verification</span><span className="complete">✓ Complete</span></span><span className="report-foot">Ready for your review<span className="report-view">View sample</span></span></button></DialogTrigger>
</div></div>
<div className="container value-strip"><div ><span className="value-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="10" cy="10" r="6"></circle><path d="m15 15 5 5 M7 10l2 2 4-4"/></svg></span><div ><h2 >Thorough by design.</h2><p >Research that goes beyond a name match.</p></div></div><div ><span className="value-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 14v-3a8 8 0 0 1 16 0v3M4 12H2v6h4v-6ZM20 12h2v6h-4v-6ZM20 18v3h-6"/></svg></span><div ><h2 >Human at heart.</h2><p >A U.S.-based team you can actually reach.</p></div></div><div ><span className="value-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="16" rx="2"></rect><path d="M8 3v4M16 3v4M4 11h16M8 16h2M14 16h2"/></svg></span><div ><h2 >Built around you.</h2><p >The right checks for the roles you hire.</p></div></div></div>
</section>
<section id="screening" className="section services-section container" aria-labelledby="screening-heading"><div className="section-intro"><div ><p className="eyebrow">A COMPLETE SCREENING PARTNER</p><h2 id="screening-heading">A better picture.<br /><em >A more confident decision.</em></h2></div><p >Every role comes with different responsibilities. Choose the checks that help you see what matters.</p></div><ServiceExplorer />
</section>
<section className="process-section"><div className="container"><div className="center-heading"><p className="eyebrow">FROM FIRST CONVERSATION TO FIRST DAY</p><h2 >A smoother path<br />to <em >your next great hire.</em></h2><p >We help you keep screening clear, organized, and moving forward.</p></div><ol className="process-grid"><li ><div className="step-top"><span >01</span><i ></i></div><h3 >Make it your own.</h3><p >Tell us about your business. We’ll help you choose a screening package that fits your roles and hiring needs.</p></li><li ><div className="step-top"><span >02</span><i ></i></div><h3 >Let us handle the details.</h3><p >Our team manages research and verification, with screening information brought together for your review.</p></li><li ><div className="step-top"><span >03</span><i ></i></div><h3 >Move forward with clarity.</h3><p >Review the results, get answers to your questions, and make an informed decision about your next hire.</p></li></ol><div className="process-action"><Link className="button button-navy" href="/talk-to-an-expert">Talk through your hiring process</Link></div></div></section>
<section id="difference" className="human-section" aria-labelledby="human-heading"><div className="container human-grid"><div className="human-photo-wrap"><div className="human-photo"><img src="/images/operations-team.webp" alt="A team reviewing screening information, from the PreciseHire website" width="1400" height="1050" loading="lazy"/></div><div className="support-label"><span className="support-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 14v-3a8 8 0 0 1 16 0v3M4 12H2v6h4v-6ZM20 12h2v6h-4v-6ZM20 18v3h-6"/></svg></span><div ><strong >Your questions deserve a person.</strong><span >U.S.-based support · McKinney, Texas</span></div></div></div><div className="human-copy"><p className="eyebrow light">REAL PEOPLE. REAL ACCOUNTABILITY.</p><h2 id="human-heading">Good technology.<br /><em >Even better people.</em></h2><p >Background screening is personal. So is the way we work with you. Get a team that understands your account, takes your questions seriously, and stays with you through the details.</p><div className="human-values"><div ><span aria-hidden="true">✓</span><p >Experienced screening specialists</p></div><div ><span aria-hidden="true">✓</span><p >Clear answers about your reports</p></div><div ><span aria-hidden="true">✓</span><p >Support for your everyday hiring needs</p></div></div><div className="human-actions"><Link className="button button-white" href="/support">Meet your support team</Link><a className="phone-link" href="tel:+18667735486">(866) 773-5486</a></div></div></div></section>
<section id="industries" className="section industry-section container" aria-labelledby="industry-heading"><div className="section-intro"><div ><p className="eyebrow">YOUR INDUSTRY. YOUR PEOPLE.</p><h2 id="industry-heading">Different worlds.<br /><em >The same careful attention.</em></h2></div><p >From a new nurse to a new driver, build a screening program around the work your people do.</p></div><div className="industry-grid"><Link href="/industries#staffing"><span className="industry-number">01</span><div ><h3 >Staffing &amp; recruiting</h3><p >Keep your placements moving.</p></div><span className="industry-link">Explore</span></Link><Link href="/industries#healthcare"><span className="industry-number">02</span><div ><h3 >Healthcare</h3><p >Care begins with the right team.</p></div><span className="industry-link">Explore</span></Link><Link href="/industries#transportation"><span className="industry-number">03</span><div ><h3 >Transportation &amp; logistics</h3><p >Confidence for the road ahead.</p></div><span className="industry-link">Explore</span></Link><Link href="/industries#nonprofit"><span className="industry-number">04</span><div ><h3 >Nonprofits &amp; communities</h3><p >Support the people you serve.</p></div><span className="industry-link">Explore</span></Link></div><div className="industry-bottom"><p >Also serving retail, hospitality, finance, and other industries.</p><Link className="quiet-link" href="/industries">View all industries</Link></div></section>
<section className="faq-section container" aria-labelledby="faq-heading"><div ><p className="eyebrow">LET’S CLEAR THINGS UP</p><h2 id="faq-heading">A few good<br /><em >questions.</em></h2><p >Have something else on your mind?<br />We’re always happy to talk.</p><Link className="quiet-link" href="/talk-to-an-expert">Speak with a specialist</Link></div><HomeQuestions /></section>
<section className="cta-section container"><div className="cta-content"><p className="eyebrow">READY FOR YOUR NEXT CHAPTER?</p><h2 >Make your next hire<br /><em >your most confident one.</em></h2><p >Tell us who you’re hiring. We’ll help with what comes next.</p><div ><Link className="button button-red" href="/get-a-quote">Let’s build your screening package</Link><span >A real conversation. A package built around you.</span></div></div><img src="/images/swoosh-red.svg" className="cta-swoosh" alt="" aria-hidden="true"/></section>
</div><ExampleReport/></Dialog></>}
